server:
  port: 8001
#mybatis配置
mybatis:
  type-aliases-package: com.feng.springcloud.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml

#spring
spring:
  application:
    name: springcloud-provider-dept-8001
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource  #数据源
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db01?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456

#Eureka 配置
eureka:
  instance:
    hostname: localhost #Eureka 服务端名称
    instance-id: springxloud-provider-8001
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:7001/eureka/
