server:
  port: 3344
spring:
  application:
    name: spring-cloud-config-server
    #链接远程仓库
  cloud:
    config:
      server:
        git:
          uri: https://github.com/waitwaitww/springcloudlearn.git