server:
  port: 9527
spring:
  application:
    name: springcloud-zuul

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/,http://localhost:7003/eureka/
  instance:
    instance-id: zuul9527
    prefer-ip-address: true
info:
  app.name: feng-springcloud
  company.name: feng

zuul:
  routes:
    mydept.serviceId: springcloud-provider-dept-8001
    mydept.path: /mydept/**
  ignored-services: springcloud-provider-dept-8001 #无法再通过该名访问
  #ignored-services: "*" #无法再通过该名访问  隐藏全部
  prefix: /feng  #设置公共前缀
